import { useState } from "react";
const V = { 50: "#F9EAED", 100: "#EDCAD0", 200: "#DCA3AD", 300: "#C97A8A", 400: "#B05A6A", 500: "#963B4D", 600: "#7B1D32", 700: "#6A1629", 800: "#520F1E", 900: "#3A0911" };
const SECTIONS = [{ title: "Que es una Macro", content: [{ type: "definition_list", items: [{ term: "Definicion", def: "Una secuencia de acciones grabadas que Excel repite automaticamente. Si todos los lunes haces lo mismo, una Macro lo hace con un clic." }, { term: "Internamente", def: "Las macros se escriben en VBA (Visual Basic for Applications). Pero puedes grabarlas sin saber programar." }, { term: "Formato .xlsm", def: "Archivos con macros se guardan como .xlsm. Si guardas como .xlsx, las macros se pierden." }] }] }, { title: "Habilitar la tab Developer", content: [{ type: "definition_list", items: [{ term: "Como", def: "File > Options > Customize Ribbon > marcar Developer. Aparece la tab con Record Macro y Visual Basic." }, { term: "Alternativa", def: "Tambien puedes grabar desde View > Macros > Record Macro." }] }] }, { title: "Record Macro — grabar paso a paso", content: [{ type: "definition_list", items: [{ term: "Iniciar", def: "Developer > Record Macro. Define nombre (sin espacios), atajo opcional (Ctrl+Shift+algo), y donde guardarla." }, { term: "Grabar", def: "Desde que haces clic en OK, cada accion queda grabada: movimientos, formato, formulas, todo." }, { term: "Detener", def: "Stop Recording cuando termines. La macro esta lista para ejecutar." }] }] }, { title: "Ejecutar y asignar a boton", content: [{ type: "definition_list", items: [{ term: "Ejecutar", def: "Developer > Macros > seleccionar > Run. O usar el atajo asignado." }, { term: "Boton", def: "Insert > Button (Form Control) > asignar la macro. El usuario solo hace clic." }, { term: "Personal Macro Workbook", def: "Guardar en Personal Macro Workbook hace la macro disponible en cualquier archivo. Ideal para macros de uso general." }] }] }, { title: "Edicion basica del codigo", content: [{ type: "definition_list", items: [{ term: "Abrir editor", def: "Alt+F11 abre el VBA Editor. El codigo grabado esta en Modules." }, { term: "Ediciones simples", def: "Cambiar valores fijos (un nombre de region, un numero), eliminar lineas .Select redundantes, duplicar la macro para crear variantes." }, { term: "No necesitas programar", def: "Para ediciones basicas solo necesitas encontrar el valor a cambiar y modificarlo." }] }] }, { title: "Limitaciones de la grabadora", content: [{ type: "definition_list", items: [{ term: "No graba logica", def: "No puede grabar decisiones (si X entonces Y). No puede grabar bucles (repite para cada hoja)." }, { term: "No interactua con otros programas", def: "No puede enviar emails ni abrir otros archivos automaticamente." }, { term: "Para eso: VBA", def: "Escribir VBA desde cero permite todo lo anterior. Es el siguiente modulo." }] }] }];
export default function Module() {
  const [openSection, setOpenSection] = useState(0);
  const renderBlock = (block, bi) => {
    if (block.type === "text") return <p key={bi} style={{ fontSize: 14, color: "var(--color-text-secondary)", margin: bi === 0 ? "0 0 14px" : "14px 0", lineHeight: 1.7 }}>{block.value}</p>;
    if (block.type === "definition_list") return (<div key={bi} style={{ display: "flex", flexDirection: "column", gap: 10, margin: "10px 0" }}>{block.items.map((item, di) => (<div key={di} style={{ background: "var(--color-background-secondary)", borderRadius: "var(--border-radius-md)", padding: "10px 14px" }}><div style={{ fontSize: 13, fontWeight: 500, color: V[600], marginBottom: 2 }}>{item.term}</div><div style={{ fontSize: 13, color: "var(--color-text-secondary)", lineHeight: 1.6 }}>{item.def}</div></div>))}</div>);
    if (block.type === "key_points") return (<div key={bi} style={{ display: "flex", flexDirection: "column", gap: 10, margin: "10px 0" }}>{block.items.map((item, ki) => (<div key={ki} style={{ borderLeft: `2px solid ${V[200]}`, paddingLeft: 14 }}><div style={{ fontSize: 13, fontWeight: 500, color: "var(--color-text-primary)", marginBottom: 3 }}>{item.title}</div><div style={{ fontSize: 13, color: "var(--color-text-secondary)", lineHeight: 1.6 }}>{item.text}</div></div>))}</div>);
    return null;
  };
  return (
    <div style={{ maxWidth: 680, margin: "0 auto", padding: "0.5rem 0 2rem" }}>
      <div style={{ marginBottom: "1.5rem" }}>
        <div style={{ display: "flex", alignItems: "center", gap: 10, marginBottom: 10 }}>
          <span style={{ fontSize: 11, fontWeight: 500, letterSpacing: "0.06em", padding: "3px 10px", borderRadius: "var(--border-radius-md)", background: V[50], color: V[800] }}>NIVEL 4 — EXCEL PRO</span>
          <span style={{ fontSize: 12, color: "var(--color-text-tertiary)" }}>Modulo 1 de 6</span>
        </div>
        <h1 style={{ fontSize: 22, fontWeight: 500, color: "var(--color-text-primary)", margin: "0 0 6px" }}>Macros: Record and Edit</h1>
        <p style={{ fontSize: 14, color: "var(--color-text-secondary)", margin: 0, lineHeight: 1.6 }}>Automatiza tareas repetitivas grabando macros y editando el codigo generado.</p>
      </div>
      <div style={{ background: V[50], borderLeft: `3px solid ${V[400]}`, borderRadius: "0 var(--border-radius-md) var(--border-radius-md) 0", padding: "12px 16px", marginBottom: "1.5rem" }}>
        <div style={{ fontSize: 11, fontWeight: 500, color: V[600], letterSpacing: "0.04em", marginBottom: 2 }}>OBJETIVO</div>
        <p style={{ fontSize: 13, color: V[800], margin: 0, lineHeight: 1.6 }}>Que puedas grabar macros, ejecutarlas, y hacer ediciones basicas al codigo VBA generado.</p>
      </div>
      <div style={{ display: "flex", flexDirection: "column", gap: 6 }}>
        {SECTIONS.map((s, si) => { const isOpen = openSection === si; return (<div key={si} style={{ borderRadius: "var(--border-radius-md)", border: `0.5px solid ${isOpen ? V[200] : "var(--color-border-tertiary)"}` }}><div onClick={() => setOpenSection(isOpen ? -1 : si)} style={{ display: "flex", alignItems: "center", gap: 12, padding: "14px 16px", cursor: "pointer" }}><div style={{ width: 28, height: 28, minWidth: 28, borderRadius: "50%", background: isOpen ? V[600] : V[50], display: "flex", alignItems: "center", justifyContent: "center", fontSize: 12, fontWeight: 500, color: isOpen ? "#fff" : V[600] }}>{si + 1}</div><span style={{ flex: 1, fontSize: 15, fontWeight: 500, color: isOpen ? V[800] : "var(--color-text-primary)" }}>{s.title}</span><span style={{ fontSize: 16, color: "var(--color-text-tertiary)", transform: isOpen ? "rotate(180deg)" : "rotate(0deg)", transition: "transform 0.2s" }}>&#x25BE;</span></div>{isOpen && <div style={{ padding: "0 16px 16px 56px" }}>{s.content.map((b, bi) => renderBlock(b, bi))}</div>}</div>); })}
      </div>
      <div style={{ background: "var(--color-background-secondary)", borderRadius: "var(--border-radius-lg)", padding: "1.25rem", marginTop: "1.5rem" }}>
        <div style={{ fontSize: 14, fontWeight: 500, color: "var(--color-text-primary)", marginBottom: 10 }}>Puntos clave</div>
        {["Record Macro graba acciones sin necesidad de programar.", "Personal Macro Workbook hace macros disponibles en cualquier archivo.", "Alt+F11 abre el VBA Editor para ediciones basicas.", "Archivos con macros se guardan como .xlsm, no .xlsx.", "La grabadora no puede grabar logica ni bucles. Para eso necesitas VBA."].map((p, i) => (
          <div key={i} style={{ display: "flex", gap: 10, alignItems: "flex-start", padding: "6px 0", borderTop: i > 0 ? "0.5px solid var(--color-border-tertiary)" : "none" }}><div style={{ width: 6, height: 6, minWidth: 6, borderRadius: "50%", background: V[400], marginTop: 7 }} /><span style={{ fontSize: 13, color: "var(--color-text-secondary)", lineHeight: 1.6 }}>{p}</span></div>))}
      </div>
      <div style={{ display: "flex", justifyContent: "space-between", alignItems: "center", marginTop: "1.5rem", paddingTop: "1rem", borderTop: "0.5px solid var(--color-border-tertiary)" }}>
        <span style={{ fontSize: 13, fontWeight: 500, color: V[600] }}>Nivel 4 — Excel Pro</span>
        <span style={{ fontSize: 13, fontWeight: 500, color: V[600] }}>Siguiente: VBA introductorio</span>
      </div>
    </div>
  );
}
