import { useState } from "react";
const V = { 50: "#F9EAED", 100: "#EDCAD0", 200: "#DCA3AD", 300: "#C97A8A", 400: "#B05A6A", 500: "#963B4D", 600: "#7B1D32", 700: "#6A1629", 800: "#520F1E", 900: "#3A0911" };
const SECTIONS = [{ title: "El entorno VBA Editor", content: [{ type: "definition_list", items: [{ term: "Abrir", def: "Alt+F11. Project Explorer a la izquierda, Properties abajo, area de codigo al centro." }, { term: "Immediate Window", def: "Ctrl+G. Permite ejecutar lineas individuales para probar. Util para depurar." }, { term: "Modules", def: "Donde vive el codigo ejecutable. Insert > Module para crear uno nuevo." }] }] }, { title: "Estructura de una Sub", content: [{ type: "definition_list", items: [{ term: "Sintaxis", def: "Sub NombreDeLaMacro() ... End Sub. Todo codigo ejecutable vive dentro de una Sub." }, { term: "Ejemplo basico", def: "Sub Saludar()  MsgBox \"Hola\"  End Sub. Crea una macro que muestra un mensaje." }, { term: "Ejecutar", def: "F5 dentro del editor, o desde Developer > Macros." }] }] }, { title: "Variables", content: [{ type: "definition_list", items: [{ term: "Declarar", def: "Dim nombreVariable As Tipo. Tipos: String (texto), Long (enteros), Double (decimales), Boolean, Date." }, { term: "Asignar", def: "miVariable = 100. O miTexto = \"Hola\". Las variables hacen el codigo flexible." }, { term: "Ejemplo", def: "Dim total As Double  total = Range(\"A1\").Value + Range(\"B1\").Value  Range(\"C1\").Value = total" }] }] }, { title: "Referenciar celdas y rangos", content: [{ type: "definition_list", items: [{ term: "Range", def: "Range(\"A1\").Value lee o escribe el valor de A1. Range(\"A1:B10\").Select selecciona un rango." }, { term: "Cells", def: "Cells(fila, columna).Value. Cells(1,1) = A1. Util en bucles porque acepta variables." }, { term: "Hojas", def: "Worksheets(\"Data\").Range(\"A1\").Value accede a una celda en una hoja especifica." }] }] }, { title: "If Then Else", content: [{ type: "definition_list", items: [{ term: "Estructura", def: "If condicion Then ... ElseIf ... Else ... End If. Permite que la macro tome decisiones." }, { term: "Ejemplo", def: "If Range(\"B2\").Value > 1000 Then Range(\"C2\").Value = \"Alto\" Else Range(\"C2\").Value = \"Normal\" End If" }] }] }, { title: "Bucles: For y Do While", content: [{ type: "definition_list", items: [{ term: "For", def: "For i = 1 To 100 ... Next i. Repite un bloque con i tomando valores del 1 al 100. Ideal para recorrer filas." }, { term: "Do While", def: "Do While Cells(i,1).Value <> \"\" ... i = i + 1 Loop. Repite mientras la celda no este vacia. Ideal para datos de longitud variable." }, { term: "For Each", def: "For Each ws In ThisWorkbook.Worksheets ... Next ws. Recorre todas las hojas de un libro." }] }] }, { title: "MsgBox e InputBox", content: [{ type: "definition_list", items: [{ term: "MsgBox", def: "Muestra mensajes al usuario. MsgBox \"Proceso completado\". Tambien puede pedir confirmacion: If MsgBox(\"Continuar?\", vbYesNo) = vbYes Then..." }, { term: "InputBox", def: "Pide un dato: region = InputBox(\"Que region?\"). Almacena la respuesta en una variable para usar despues." }] }] }];
export default function Module() {
  const [openSection, setOpenSection] = useState(0);
  const renderBlock = (block, bi) => {
    if (block.type === "text") return <p key={bi} style={{ fontSize: 14, color: "var(--color-text-secondary)", margin: bi === 0 ? "0 0 14px" : "14px 0", lineHeight: 1.7 }}>{block.value}</p>;
    if (block.type === "definition_list") return (<div key={bi} style={{ display: "flex", flexDirection: "column", gap: 10, margin: "10px 0" }}>{block.items.map((item, di) => (<div key={di} style={{ background: "var(--color-background-secondary)", borderRadius: "var(--border-radius-md)", padding: "10px 14px" }}><div style={{ fontSize: 13, fontWeight: 500, color: V[600], marginBottom: 2 }}>{item.term}</div><div style={{ fontSize: 13, color: "var(--color-text-secondary)", lineHeight: 1.6 }}>{item.def}</div></div>))}</div>);
    if (block.type === "key_points") return (<div key={bi} style={{ display: "flex", flexDirection: "column", gap: 10, margin: "10px 0" }}>{block.items.map((item, ki) => (<div key={ki} style={{ borderLeft: `2px solid ${V[200]}`, paddingLeft: 14 }}><div style={{ fontSize: 13, fontWeight: 500, color: "var(--color-text-primary)", marginBottom: 3 }}>{item.title}</div><div style={{ fontSize: 13, color: "var(--color-text-secondary)", lineHeight: 1.6 }}>{item.text}</div></div>))}</div>);
    return null;
  };
  return (
    <div style={{ maxWidth: 680, margin: "0 auto", padding: "0.5rem 0 2rem" }}>
      <div style={{ marginBottom: "1.5rem" }}>
        <div style={{ display: "flex", alignItems: "center", gap: 10, marginBottom: 10 }}>
          <span style={{ fontSize: 11, fontWeight: 500, letterSpacing: "0.06em", padding: "3px 10px", borderRadius: "var(--border-radius-md)", background: V[50], color: V[800] }}>NIVEL 4 — EXCEL PRO</span>
          <span style={{ fontSize: 12, color: "var(--color-text-tertiary)" }}>Modulo 2 de 6</span>
        </div>
        <h1 style={{ fontSize: 22, fontWeight: 500, color: "var(--color-text-primary)", margin: "0 0 6px" }}>VBA introductorio</h1>
        <p style={{ fontSize: 14, color: "var(--color-text-secondary)", margin: 0, lineHeight: 1.6 }}>Variables, Loops, If Then, MsgBox, InputBox. Escribe tus propias Macros desde cero.</p>
      </div>
      <div style={{ background: V[50], borderLeft: `3px solid ${V[400]}`, borderRadius: "0 var(--border-radius-md) var(--border-radius-md) 0", padding: "12px 16px", marginBottom: "1.5rem" }}>
        <div style={{ fontSize: 11, fontWeight: 500, color: V[600], letterSpacing: "0.04em", marginBottom: 2 }}>OBJETIVO</div>
        <p style={{ fontSize: 13, color: V[800], margin: 0, lineHeight: 1.6 }}>Que entiendas la estructura basica de VBA y puedas escribir macros simples desde cero.</p>
      </div>
      <div style={{ display: "flex", flexDirection: "column", gap: 6 }}>
        {SECTIONS.map((s, si) => { const isOpen = openSection === si; return (<div key={si} style={{ borderRadius: "var(--border-radius-md)", border: `0.5px solid ${isOpen ? V[200] : "var(--color-border-tertiary)"}` }}><div onClick={() => setOpenSection(isOpen ? -1 : si)} style={{ display: "flex", alignItems: "center", gap: 12, padding: "14px 16px", cursor: "pointer" }}><div style={{ width: 28, height: 28, minWidth: 28, borderRadius: "50%", background: isOpen ? V[600] : V[50], display: "flex", alignItems: "center", justifyContent: "center", fontSize: 12, fontWeight: 500, color: isOpen ? "#fff" : V[600] }}>{si + 1}</div><span style={{ flex: 1, fontSize: 15, fontWeight: 500, color: isOpen ? V[800] : "var(--color-text-primary)" }}>{s.title}</span><span style={{ fontSize: 16, color: "var(--color-text-tertiary)", transform: isOpen ? "rotate(180deg)" : "rotate(0deg)", transition: "transform 0.2s" }}>&#x25BE;</span></div>{isOpen && <div style={{ padding: "0 16px 16px 56px" }}>{s.content.map((b, bi) => renderBlock(b, bi))}</div>}</div>); })}
      </div>
      <div style={{ background: "var(--color-background-secondary)", borderRadius: "var(--border-radius-lg)", padding: "1.25rem", marginTop: "1.5rem" }}>
        <div style={{ fontSize: 14, fontWeight: 500, color: "var(--color-text-primary)", marginBottom: 10 }}>Puntos clave</div>
        {["Alt+F11 abre el VBA Editor. El codigo vive en Modules.", "Sub ... End Sub es la estructura basica. F5 para ejecutar.", "Range(\"A1\").Value para leer/escribir celdas. Cells(fila,col) para bucles.", "If Then para decisiones. For/Do While para repetir acciones.", "MsgBox muestra mensajes. InputBox pide datos al usuario."].map((p, i) => (
          <div key={i} style={{ display: "flex", gap: 10, alignItems: "flex-start", padding: "6px 0", borderTop: i > 0 ? "0.5px solid var(--color-border-tertiary)" : "none" }}><div style={{ width: 6, height: 6, minWidth: 6, borderRadius: "50%", background: V[400], marginTop: 7 }} /><span style={{ fontSize: 13, color: "var(--color-text-secondary)", lineHeight: 1.6 }}>{p}</span></div>))}
      </div>
      <div style={{ display: "flex", justifyContent: "space-between", alignItems: "center", marginTop: "1.5rem", paddingTop: "1rem", borderTop: "0.5px solid var(--color-border-tertiary)" }}>
        <span style={{ fontSize: 13, fontWeight: 500, color: V[600] }}>Anterior: Macros Record and Edit</span>
        <span style={{ fontSize: 13, fontWeight: 500, color: V[600] }}>Siguiente: Power Pivot y Data Model</span>
      </div>
    </div>
  );
}
