import { useState } from "react";
const V = { 50: "#F9EAED", 100: "#EDCAD0", 200: "#DCA3AD", 300: "#C97A8A", 400: "#B05A6A", 500: "#963B4D", 600: "#7B1D32", 700: "#6A1629", 800: "#520F1E", 900: "#3A0911" };
const SECTIONS = [{ title: "El problema que resuelve", content: [{ type: "definition_list", items: [{ term: "Sin Power Pivot", def: "Para cruzar tablas necesitas XLOOKUP o INDEX+MATCH. Con 10 columnas de 3 tablas, es insostenible." }, { term: "Con Power Pivot", def: "Relacionas tablas directamente (como base de datos) y analizas con PivotTables sin formulas de busqueda." }, { term: "Volumen", def: "El Data Model maneja millones de filas que serian imposibles en hojas normales." }] }] }, { title: "Habilitar y agregar datos", content: [{ type: "definition_list", items: [{ term: "Habilitar", def: "File > Options > Add-ins > COM Add-ins > marcar Microsoft Power Pivot for Excel." }, { term: "Agregar datos", def: "Power Pivot > Add to Data Model, o al crear PivotTable marcar Add this data to the Data Model." }, { term: "Manage", def: "Power Pivot > Manage abre el editor de Data Model con vista de datos y vista de diagrama." }] }] }, { title: "Relationships", content: [{ type: "definition_list", items: [{ term: "Crear", def: "Power Pivot > Manage > Diagram View. Arrastra un campo de una tabla a otro para crear la relacion." }, { term: "Tipo", def: "Las relaciones son uno-a-muchos. Ejemplo: un ProductID en Products aparece muchas veces en Sales." }, { term: "Resultado", def: "Una PivotTable puede usar campos de ambas tablas sin XLOOKUP." }] }] }, { title: "Introduccion a DAX", content: [{ type: "definition_list", items: [{ term: "SUM", def: "=SUM(Sales[Amount]). Suma toda la columna en contexto. El contexto lo definen los filtros de la PivotTable." }, { term: "CALCULATE", def: "=CALCULATE(SUM(Sales[Amount]), Products[Category]=\"Electronics\"). Modifica el contexto de filtro. La funcion mas importante de DAX." }, { term: "SUMX", def: "=SUMX(Sales, Sales[Quantity]*Sales[UnitPrice]). Iterador: recorre fila por fila y suma el calculo." }, { term: "RELATED", def: "=RELATED(Products[Category]). Trae valor de tabla relacionada. Solo en Calculated Columns." }] }] }, { title: "Measures vs Calculated Columns", content: [{ type: "definition_list", items: [{ term: "Calculated Column", def: "Agrega columna a la tabla. Se almacena en memoria. Calcula fila por fila. Para atributos fijos." }, { term: "Measure", def: "Se calcula dinamicamente segun el contexto de la PivotTable. Para metricas de reporte." }, { term: "Regla", def: "Si depende del contexto del reporte, usa Measure. Si es un atributo fijo de cada fila, usa Calculated Column." }] }] }];
export default function Module() {
  const [openSection, setOpenSection] = useState(0);
  const renderBlock = (block, bi) => {
    if (block.type === "text") return <p key={bi} style={{ fontSize: 14, color: "var(--color-text-secondary)", margin: bi === 0 ? "0 0 14px" : "14px 0", lineHeight: 1.7 }}>{block.value}</p>;
    if (block.type === "definition_list") return (<div key={bi} style={{ display: "flex", flexDirection: "column", gap: 10, margin: "10px 0" }}>{block.items.map((item, di) => (<div key={di} style={{ background: "var(--color-background-secondary)", borderRadius: "var(--border-radius-md)", padding: "10px 14px" }}><div style={{ fontSize: 13, fontWeight: 500, color: V[600], marginBottom: 2 }}>{item.term}</div><div style={{ fontSize: 13, color: "var(--color-text-secondary)", lineHeight: 1.6 }}>{item.def}</div></div>))}</div>);
    if (block.type === "key_points") return (<div key={bi} style={{ display: "flex", flexDirection: "column", gap: 10, margin: "10px 0" }}>{block.items.map((item, ki) => (<div key={ki} style={{ borderLeft: `2px solid ${V[200]}`, paddingLeft: 14 }}><div style={{ fontSize: 13, fontWeight: 500, color: "var(--color-text-primary)", marginBottom: 3 }}>{item.title}</div><div style={{ fontSize: 13, color: "var(--color-text-secondary)", lineHeight: 1.6 }}>{item.text}</div></div>))}</div>);
    return null;
  };
  return (
    <div style={{ maxWidth: 680, margin: "0 auto", padding: "0.5rem 0 2rem" }}>
      <div style={{ marginBottom: "1.5rem" }}>
        <div style={{ display: "flex", alignItems: "center", gap: 10, marginBottom: 10 }}>
          <span style={{ fontSize: 11, fontWeight: 500, letterSpacing: "0.06em", padding: "3px 10px", borderRadius: "var(--border-radius-md)", background: V[50], color: V[800] }}>NIVEL 4 — EXCEL PRO</span>
          <span style={{ fontSize: 12, color: "var(--color-text-tertiary)" }}>Modulo 3 de 6</span>
        </div>
        <h1 style={{ fontSize: 22, fontWeight: 500, color: "var(--color-text-primary)", margin: "0 0 6px" }}>Power Pivot y Data Model</h1>
        <p style={{ fontSize: 14, color: "var(--color-text-secondary)", margin: 0, lineHeight: 1.6 }}>Relationships entre tablas, medidas DAX: CALCULATE, SUMX, RELATED. Millones de filas.</p>
      </div>
      <div style={{ background: V[50], borderLeft: `3px solid ${V[400]}`, borderRadius: "0 var(--border-radius-md) var(--border-radius-md) 0", padding: "12px 16px", marginBottom: "1.5rem" }}>
        <div style={{ fontSize: 11, fontWeight: 500, color: V[600], letterSpacing: "0.04em", marginBottom: 2 }}>OBJETIVO</div>
        <p style={{ fontSize: 13, color: V[800], margin: 0, lineHeight: 1.6 }}>Que puedas trabajar con multiples tablas relacionadas y crear analisis con DAX basico.</p>
      </div>
      <div style={{ display: "flex", flexDirection: "column", gap: 6 }}>
        {SECTIONS.map((s, si) => { const isOpen = openSection === si; return (<div key={si} style={{ borderRadius: "var(--border-radius-md)", border: `0.5px solid ${isOpen ? V[200] : "var(--color-border-tertiary)"}` }}><div onClick={() => setOpenSection(isOpen ? -1 : si)} style={{ display: "flex", alignItems: "center", gap: 12, padding: "14px 16px", cursor: "pointer" }}><div style={{ width: 28, height: 28, minWidth: 28, borderRadius: "50%", background: isOpen ? V[600] : V[50], display: "flex", alignItems: "center", justifyContent: "center", fontSize: 12, fontWeight: 500, color: isOpen ? "#fff" : V[600] }}>{si + 1}</div><span style={{ flex: 1, fontSize: 15, fontWeight: 500, color: isOpen ? V[800] : "var(--color-text-primary)" }}>{s.title}</span><span style={{ fontSize: 16, color: "var(--color-text-tertiary)", transform: isOpen ? "rotate(180deg)" : "rotate(0deg)", transition: "transform 0.2s" }}>&#x25BE;</span></div>{isOpen && <div style={{ padding: "0 16px 16px 56px" }}>{s.content.map((b, bi) => renderBlock(b, bi))}</div>}</div>); })}
      </div>
      <div style={{ background: "var(--color-background-secondary)", borderRadius: "var(--border-radius-lg)", padding: "1.25rem", marginTop: "1.5rem" }}>
        <div style={{ fontSize: 14, fontWeight: 500, color: "var(--color-text-primary)", marginBottom: 10 }}>Puntos clave</div>
        {["Power Pivot relaciona tablas sin formulas de busqueda.", "Diagram View para crear Relationships arrastrando campos.", "CALCULATE modifica el contexto de filtro. Es la funcion clave de DAX.", "SUMX itera fila por fila. RELATED trae datos de tablas relacionadas.", "Measures para metricas dinamicas. Calculated Columns para atributos fijos."].map((p, i) => (
          <div key={i} style={{ display: "flex", gap: 10, alignItems: "flex-start", padding: "6px 0", borderTop: i > 0 ? "0.5px solid var(--color-border-tertiary)" : "none" }}><div style={{ width: 6, height: 6, minWidth: 6, borderRadius: "50%", background: V[400], marginTop: 7 }} /><span style={{ fontSize: 13, color: "var(--color-text-secondary)", lineHeight: 1.6 }}>{p}</span></div>))}
      </div>
      <div style={{ display: "flex", justifyContent: "space-between", alignItems: "center", marginTop: "1.5rem", paddingTop: "1rem", borderTop: "0.5px solid var(--color-border-tertiary)" }}>
        <span style={{ fontSize: 13, fontWeight: 500, color: V[600] }}>Anterior: VBA introductorio</span>
        <span style={{ fontSize: 13, fontWeight: 500, color: V[600] }}>Siguiente: Conexion a fuentes externas</span>
      </div>
    </div>
  );
}
